---
# file: all.yml
- hosts: all
  roles:
    - common
    - cloudera_node
  environment:
    - "{{ proxy_env }}"

- hosts: cloudera_manager
  roles:
    - cloudera_manager_setup
  environment:
    - "{{ proxy_env }}"
