---
# file: roles/cloudera_manager_setup/tasks/main.yml
- name: download cloudera manager installer
  get_url:
    url: https://archive.cloudera.com/cm5/installer/latest/cloudera-manager-installer.bin
    dest: /root/cloudera-manager-installer.bin
    owner: root
    group: root
    mode: 0700
