---
# file: roles/hadoop_presetup/tasks/main.yml
- name: create partition
  command: parted /dev/{{item.dev}} mklabel gpt -- mkpart primary ext4 1 -1
  when: ansible_devices.{{item.dev}}.partitions.{{item.dev}}1 is not defined
  with_items: hadoop_storage

- name: format for hdfs disk.
  filesystem: fstype=ext4 dev=/dev/{{item.dev}}1
  with_items: hadoop_storage

- name: mount device for hdfs
  mount: name={{item.mount_point}} src=/dev/{{item.dev}}1 fstype=ext4 state=mounted
  with_items: hadoop_storage
